FULL_AMOUNT_PAID = 1000 * 32.87
COMMISSION_PAID = 657.4
FULL_AMOUNT_SOLD = 1000 * 33.92
COMMISSION_SOLD = 678.4
COMMISSION_TOTAL = COMMISSION_PAID + COMMISSION_SOLD
A = FULL_AMOUNT_SOLD - COMMISSION_TOTAL
if (A > FULL_AMOUNT_PAID):
    print("Profit Gained!")
else:
    print("Profit lost.")